### ISSUE TITLE
Failure to build on Windows

### ISSUE THREAD

**Issue by JohnDoneth** [wasmerio/wasmer-rust-example#3]
On the latest stable version of Rust I have encountered the following error when trying to build the example.
```
   Compiling wasmer-runtime-core v0.1.2
error[E0432]: unresolved import `self::memory`
 --> C:\Users\Donet\.cargo\registry\src\github.com-1ecc6299db9ec823\wasmer-runtime-core-0.1.2\src\sys\windows\mod.rs:1:15
  |
1 | pub use self::memory::{Memory, Protect};
  |               ^^^^^^ could not find `memory` in `self`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0432`.
error: Could not compile `wasmer-runtime-core`.
```

**Comment by JohnDoneth** [comment]
~~I have isolated the issue to a single missing `mod memory;` that exists in the Unix build configuration but not the Windows build configuration which is probably how it slipped past release of the crate.~~

Windows support issue: https://github.com/wasmerio/wasmer/issues/51

**Comment by syrusakbary** [comment]
The latest changes in #5 (wasmer 0.2.0) make the example run on Windows perfectly :)

Closing the issue
